"NAME","BASEURL__C","DIGITAL_ANNUALLY_ID__C","DIGITAL_MONTHLY_ID__C","DISABLE_FRAMES__C","LOGIN__C","PASSWORD__C","PREMIUM_CONTINUOUS_ID__C","URL__C"
"MPP","https://paymentsxxx-uat.telegraph.co.uk/","11169","11168","false","435","Ee8xxxx","11249","https://paymentsxxx-uat.telegraph.co.uk/interface/mpp/iPayPaymentPages/iPayPaymentPages.asmx"
"SAM","https://authxxxx-uat.telegraph.co.uk/","","","false","359dd847-757b-4795-8c8c-cf895c2xxxx","","","http://authxxx-uat.telegraph.co.uk/eventBroker/services/SalesforceService"
"ExactTarget","","","","false","marketing@telegraph.co.uk","a65432x!","","https://xxxxx.s4.telegraph.co.uk/integrate.aspx"
